FROM node:18

RUN mkdir -p /home/app2

# Copy the application files into the container
COPY ["package.json","package-lock.json*","./"]

COPY . .

COPY . /home/app2

EXPOSE 3004

CMD ["npm","run","dev"]