FROM node:18

WORKDIR /usr/src/server_A
# Copy the application files into the container
COPY package*.json ./

COPY . .

RUN npm install

RUN npm install -g nodemon

COPY . /usr/src/server_A

EXPOSE "${NODE_PORT}"

CMD ["npm","run","dev"]