version: "3.8"
services:
  app-2:
    container_name: "SERVER_A"
    build: 
      context: .
      dockerfile: ./dockerFile
    environment:
      - NODE_OPTIONS=--max_old_space_size=8000
    ports:
      - "${NODE_PORT}:${NODE_PORT_MAPPED}"
    volumes:
      - .:/usr/src/server_A
    env_file:
      - .env
    networks:
      - claro
      - claro_shared_network
  mysql1:
    container_name: DB_A
    image: mysql:8.1.0
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT_MAPPED}"
    environment:
      MSQL_OPTS: --skip-host-cache
    restart: always
    env_file:
      - .env
    volumes:
      - mysqldata1:/var/lib/mysql
    networks:
      - claro
volumes:
  mysqldata1:
networks:
  claro:
  claro_shared_network:
    external : true
